# -*- coding: utf-8 -*-
"""Unique length top-ups — one sentence per id, never reused."""

CONTENT_TOPUP = {
    1: " Mixed thread genders on opposite ends are fine when both codes appear on the RFQ.",
    2: " Call out raised-face or flat-face preference before FerruleX locks the flange blank.",
    3: " Stroke length and corrugation count are selected against the travel you list on the quote.",
    4: " Electropolish or surface-finish notes belong on the same RFQ if the hose sits in a validated zone.",
    5: " Coupler gender on each end must be stated so the assembly arrives ready to click together.",
    6: " Centering rings and clamps can ship with the hose or be sourced locally — say which on the RFQ.",
    7: " Fully annealed tube below the recommended hardness range seals more reliably on gas service.",
    8: " Gauge the female thread before ordering mixed BSPP and NPT lots on one manifold drawing.",
    9: " Leave straight tube beyond each nut so ferrules seat without fighting a nearby bend.",
    10: " List the larger OD first in notes so purchasing and the factory read the same reducing direction.",
    11: " Orient the male thread before final ferrule pull-up so the elbow is not fighting the port.",
    12: " Union elbows remove cold-bend risk that kinks thin-wall tube and ruins sealing surfaces.",
    13: " Unused branches should be plugged during commissioning rather than left open to collect debris.",
    14: " The branch cannot automatically carry full run pressure if wall thickness differs on that leg.",
    15: " Measure thread engagement depth and any undercut before assuming a standard male connector fits.",
    16: " Drill the panel hole to the recommended diameter so the locknut seats flat without tilt.",
    17: " Keep BOM notes clear for each hybrid SKU so the warehouse does not issue a full-compression twin.",
    18: " Support nearby tubing; a cross should not be the only structural member in the manifold.",
    19: " Electropolish or passivation certificates can be added on the same RFQ when QA requires them.",
    20: " Do not substitute a standard machined union if the specification names ground finish explicitly.",
    21: " Keep finish grades segregated in stores so a rough body never lands on a show panel.",
    22: " Align the elbow so the ground face outward if only one side is customer-visible after FAT.",
    23: " Forge heat numbers can be stamped when your inspector requires them on the packing list.",
    24: " Equal and reducing forged tees should be labeled separately so the wrong blank never reaches the skid.",
    25: " If the branch sees pulsing sample flow, add a root valve on that leg during design review.",
    26: " Check panel hole clearance; forged crosses are heavier than light bar-stock crosses.",
    27: " Do not reuse a nut that was over-tightened onto scored tube — grab quality suffers.",
    28: " Confirm male versus female thread ends before the blank is selected from stock bins.",
    29: " Use sealant only on the male thread make-up, never inside the quick-screw tube bore.",
    30: " Cut both tube ends square so each side inserts to the same depth on the union.",
    31: " Leave free length after the elbow so tube is not strained against a cover plate.",
    32: " Cap unused branches with matching plugs during phased commissioning of air circuits.",
    33: " Keep a spare locknut in the kit; it is the part most often dropped inside cabinets.",
    34: " A barb without a clamp is unfinished — specify ear, worm or crimp clamps with the hose.",
    35: " Always use the ferrules that ship with the kit; mixing used ferrules invites leaks.",
    36: " Order a few extra inserts per OD; they disappear easily in field service bags.",
    37: " Apply anti-gall compound appropriate to the media when seating stainless into stainless.",
    38: " Hex heads can be stamp-coded if QA wants each plugged port identified after FAT.",
    39: " The flange does not replace a gasket unless the block drawing calls for that seal method.",
    40: " Start the plug by hand before wrenching so the shoulder finds the seat without cross-threading.",
    41: " Check guard clearance; square heads stand proud of socket plugs on mobile equipment.",
    42: " If one side is tapered and the other parallel, confirm tape versus washer sealing on the RFQ.",
    43: " Make up the fixed port before the hose end so the elbow does not clock wrong under torque.",
    44: " Consider orientation and drain legs on wet air headers where condensate collects in the tee.",
    45: " Protect threads on weld-by-thread variants from weld heat with caps and purge practice.",
    46: " Operate fully open or closed; throttling on a ball seat shortens seat life quickly.",
    47: " Wall clearance and handle swing must be checked against the enclosure drawing before lock-in.",
    48: " Exercise every path during FAT so L-port versus T-port mistakes show up before ship.",
    49: " Do not force hard instrumentation tube into quick-screw ends meant for soft tube OD.",
    50: " Color-coded handles keep multi-circuit air panels readable when several 3-ways sit together.",
    51: " Support heavy actuators if automation is added later; body threads are not pipe hangers.",
    52: " Confirm which port is inlet when seats are directional on the angle body you select.",
    53: " Tag each port on the body during install so operators match the P&ID without guessing.",
    54: " Cap weld bevels in transit and keep seats cool during welding to avoid post-weld leaks.",
    55: " Use light wrench make-up on tiny threads; mini handles round off easily under impact tools.",
    56: " Match upstream fittings to the same HP class or the valve rating is meaningless in service.",
    57: " Place the valve upstream of the FRL so filters can be serviced with the header isolated.",
    58: " Replace ferrules if an HP gas joint is remade; reused ferrules are a common leak source.",
    59: " Check handle interference against hex corners when valves sit side-by-side in a dense row.",
    60: " Extended levers need a clear swing arc beside cable trays and neighboring instruments.",
    61: " Open slowly on high differential pressure to avoid stem wear and seat wire-drawing.",
    62: " Leave stem clearance under gauges so metering does not require removing the instrument.",
    63: " Tube supports still matter; forged bodies help, but unsupported tube fatigues beside the valve.",
    64: " Protect seats from weld heat with purge and cooling so the needle still meters smoothly.",
    65: " Female ports take short nipples into gauges without stacking extra adapters on the block.",
    66: " Write both thread callouts on the PO so receiving does not reverse gender on arrival.",
    67: " Verify handle swing before drilling the plate or panel-depth savings disappear at the door.",
    68: " Ask for hydrostatic certificates when the end user requires them on the same RFQ package.",
    69: " Keep hardness in the double-ferrule range; over-hard BA tube leaks on gas make-up.",
    70: " Square-cut and deburr every stick; tight OD tolerance cannot seal a burred tube end.",
    71: " Cap coil ends in storage so moisture does not stain the ID before the first cut.",
    72: " Specify end caps for export if open corrugated blanks ship internationally without finishing.",
    73: " Place clamps near direction changes and heavy valves where vibration mass concentrates.",
    74: " Keep tube ovality in check after unreeling or the grab ring will not seat evenly.",
    75: " Keep a short straight segment into the elbow so the grab ring reaches full depth.",
    76: " Mark insertion depth during training so technicians seat tube fully on every remake.",
    77: " Tighten the bulkhead nut to the panel before inserting tube to avoid twisting the ring.",
    78: " Choose Y when a sharp T has caused noise or erosion on prior utility headers.",
    79: " Check ID finish if the line is sanitary; cast may need polish beyond as-cast surfaces.",
    80: " Label equal versus reducing cast tees in the crib — bodies look alike until ports are gauged.",
    82: " Confirm pressure class before using cast utility valves on elevated HP service.",
    84: " Match silencer flow to the valve exhaust path or cylinder return time will suffer.",
}

SUBTITLE_TOPUP = {
    3: " Provide hot and cold setpoints plus installed length so corrugation travel is not undersized on first article.",
    59: " Short handles are available when adjacent instruments leave little swing room on the hex row.",
    60: " Bright handle covers help operators read open versus closed from across a dark skid aisle.",
    64: " If future service must remove the valve, reconsider compression ends instead of permanent welds.",
    75: " Left and right orientations can be bagged separately when molded tube exits dictate a handed elbow.",
}

